### ISSUE TITLE
NextJS 11.x

### ISSUE THREAD

**Issue by haf** [stackbit/sourcebit-target-next#13]
This package is according to its dependencies forcing us to stay with NextJS 10 rather than being able to upgrade to v11.

It should be possible to upgrade to NextJS v11 without much breakage (looks fine in the browser, when I upgrade), but it needs to be tested and verified.

**Comment by smnh** [comment]
Updated nextjs peer dependency to >= 10.
Released sourcebit-target-next@0.6.4.
